import {
  Archive,
  BadgeCheck,
  Banknote,
  Bot,
  Box,
  Boxes,
  Briefcase,
  Brush,
  Building,
  Building2,
  CalendarArrowUp,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  Car,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CirclePlay,
  CircleX,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Columns3,
  CreditCard,
  Crosshair,
  DoorClosed,
  DoorOpen,
  Ear,
  Eye,
  FileBarChart,
  FilePen,
  FileSignature,
  FileSpreadsheet,
  FileText,
  Filter,
  Flame,
  Folder,
  Gauge,
  Globe,
  GraduationCap,
  Hand,
  Handshake,
  HardHat,
  History,
  Hourglass,
  Image,
  Inbox,
  Info,
  KeyRound,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Library,
  Link,
  Link2,
  List,
  ListChecks,
  Mail,
  MailCheck,
  MailPlus,
  MapPin,
  MapPinned,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessageSquareText,
  Moon,
  Music,
  Newspaper,
  Package,
  PackagePlus,
  Palette,
  PauseCircle,
  Phone,
  PhoneCall,
  Plug,
  Presentation,
  QrCode,
  Radio,
  Receipt,
  ReceiptText,
  RefreshCw,
  Route,
  Scissors,
  Search,
  Send,
  SendHorizontal,
  Settings,
  Settings2,
  Shapes,
  ShieldCheck,
  ShieldOff,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Snowflake,
  Sparkles,
  Speech,
  Star,
  Store,
  Table,
  Tag,
  Tags,
  Target,
  Telescope,
  Trash2,
  TrendingUp,
  ThumbsUp,
  Truck,
  Type,
  User,
  Users,
  UsersRound,
  Video,
  Wrench,
  Dot,
  type LucideIcon,
} from "lucide-react";

/**
 * A glyph for every L3 row, by label.
 *
 * L3 rows inherited their parent's icon for one revision, which was wrong: a
 * panel of six rows all wearing the Sites glyph tells you nothing you did not
 * already know from the heading above them. An L3 is a destination — it can be
 * pinned and promoted out to L2 or L1 — so it has to carry its own meaning,
 * not its parent's.
 *
 * Keyed on the LABEL rather than the id, because the same label recurs under
 * different parents — "Settings", "All", "Dashboard" — and those genuinely are
 * the same kind of place. Two Settings rows sharing a gear is right; a Settings
 * row and a Reviews row sharing one is not.
 */
const LABEL_ICONS: Record<string, LucideIcon> = {
  "Abandoned Checkout": ShoppingCart,
  "Accepted": CircleCheck,
  "Accounting Sync": Landmark,
  "Active": CirclePlay,
  "Affiliate": Handshake,
  "Agent": Bot,
  "Agents List": Bot,
  "All": List,
  "All Integrations": Plug,
  "All Invoices": Receipt,
  "All accounts": Building2,
  "All pipelines": Columns3,
  "All snippets": Scissors,
  "All templates": LayoutTemplate,
  "Analytics": ChartLine,
  "Analyze": ChartPie,
  "App Permissions": ShieldCheck,
  "App Settings": Settings2,
  "Appointment": CalendarCheck,
  "Appointments": CalendarCheck,
  "Approved": BadgeCheck,
  "Archived": Archive,
  "Ask AI Evaluations": ClipboardCheck,
  "Assessments": GraduationCap,
  "Attribution": Route,
  "Availability": CalendarClock,
  "Blogs": Newspaper,
  "Brand voice": Speech,
  "Branded Mobile App": Smartphone,
  "Branding": Brush,
  "Browse marketplace": Store,
  "Business": Building,
  "Call": Phone,
  "Campaign": Megaphone,
  "Campaigns": Megaphone,
  "Car": Car,
  "Chat Widget": MessageSquare,
  "Closing this month": CalendarRange,
  "Collections": Boxes,
  "Comments": MessageSquareText,
  "Completed": CircleCheckBig,
  "Connections": Link,
  "Contact": User,
  "Contacts": Users,
  "Content": FileText,
  "Content library": Library,
  "Conversation Providers": Radio,
  "Custom Domain": Globe,
  "Custom Emails": MailPlus,
  "Custom objects": Shapes,
  "Dashboard": LayoutDashboard,
  "Dashboard Settings": SlidersHorizontal,
  "Dashboards": LayoutDashboard,
  "Declined": CircleX,
  "Deleted": Trash2,
  "Design kit": Palette,
  "Do today": CalendarCheck2,
  "Domain Setup": Globe,
  "Draft": FilePen,
  "Drafts": FilePen,
  "Eliza Service": Sparkles,
  "Email Services": Mail,
  "Email Settings": MailCheck,
  "Engagement Score": Gauge,
  "Estimates": FileSpreadsheet,
  "Expired": CalendarX,
  "External Tracking": Crosshair,
  "Facebook": ThumbsUp,
  "Folders": Folder,
  "Forms": ClipboardList,
  "Funnel": Filter,
  "Funnels": Filter,
  "GBP Optimisation": MapPin,
  "Google Ads": Search,
  "Groups": UsersRound,
  "Hot leads": Flame,
  "Image": Image,
  "In service": Wrench,
  "Inbox": Inbox,
  "Inventory": Package,
  "Invoiced": ReceiptText,
  "Invoices": Receipt,
  "Key accounts": Star,
  "Language Settings": Languages,
  "LinkedIn": Briefcase,
  "Links": Link2,
  "Listings": MapPinned,
  "Local Marketing Audit": ClipboardCheck,
  "Manual Actions": Hand,
  "Media": Image,
  "Meetings": Video,
  "Membership Analytics": ChartLine,
  "Membership Settings": Settings2,
  "Meta Ads": ThumbsUp,
  "Metrics": Gauge,
  "My open deals": Briefcase,
  "Needs review": Eye,
  "New installs": PackagePlus,
  "No activity 30d": Moon,
  "Occupied": DoorClosed,
  "Offer Details": Tag,
  "Offer Upsell": TrendingUp,
  "Offers List": Tags,
  "Opportunity": Target,
  "Order List": ShoppingBag,
  "Out of warranty": ShieldOff,
  "Overview": LayoutDashboard,
  "Payments": CreditCard,
  "Payout": Banknote,
  "Pending": Clock,
  "Phone System": PhoneCall,
  "Pipeline": Columns3,
  "Planner": CalendarDays,
  "Preferences": SlidersHorizontal,
  "Product List": Package,
  "Product Progress": TrendingUp,
  "Products": Package,
  "Prospect AI": Telescope,
  "Public documents": FileText,
  "QR codes": QrCode,
  "Recurring Invoices": RefreshCw,
  "Renewals due": CalendarClock,
  "Rentals": KeyRound,
  "Report builder": Table,
  "Requests": Send,
  "Reviews": Star,
  "SEO": Search,
  "Scheduled": CalendarPlus,
  "Sent": SendHorizontal,
  "Service contracts": FileSignature,
  "Services": Wrench,
  "Sessions": History,
  "Settings": Settings,
  "Site Details": Info,
  "Snippets": Scissors,
  "Social Listening": Ear,
  "Stalled 14d": PauseCircle,
  "Standard objects": Box,
  "Statistics": ChartColumn,
  "Subcontractors": HardHat,
  "Summary": FileBarChart,
  "Suppliers": Truck,
  "Surveys": ListChecks,
  "Tags": Tag,
  "Templates": LayoutTemplate,
  "Text": Type,
  "TikTok": Music,
  "Trash": Trash2,
  "Trigger Links": Link2,
  "Unapproved": CircleAlert,
  "Upcoming": CalendarArrowUp,
  "Vacant": DoorOpen,
  "Video Testimonials": Video,
  "Waiting for others": Hourglass,
  "Webinars": Presentation,
  "Website": Globe,
  "Websites": Globe,
  "Whatsapp": MessageCircle,
  "Widgets": LayoutGrid,
  "Winter service due": Snowflake,
};

/**
 * The glyph for a child row.
 *
 * Falls back to a dot rather than to the parent: an unmapped row should look
 * like a row nobody has chosen an icon for, which is a thing to fix, instead of
 * quietly impersonating its parent.
 */
export function iconForChildLabel(label: string): LucideIcon {
  return LABEL_ICONS[label] ?? Dot;
}
